title: Igor GryzÅ‚o
logo: Igor_Portfolio/obraz_2025-01-02_134258846.png
description: >
  <ul>
    <li>Based in Cracow, PL</li>
    <li>My CV in PDF <a href="https://github.com/user-attachments/files/18286781/CV.Igor.ze.zdjeciem.pdf">Click</a></li>
    <li>My LinkedIn <a href="https://www.linkedin.com/in/igor-gryzlo/">Click</a></li>
    <li>E-Mail Address - igorgryzlo1@gmail.com</li>
  </ul>
show_downloads: false
theme: jekyll-theme-minimal
